dist: bionic
language: c++
addons:
  apt:
    packages:
      - build-essential
      - libc6-dev-i386
      - linux-libc-dev:i386
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - gcc-7-multilib
      - gcc-7-aarch64-linux-gnu
      - gcc-7-powerpc-linux-gnu
      - gcc-aarch64-linux-gnu
      - gcc-powerpc-linux-gnu
      - libc6-arm64-cross
      - libc6-powerpc-cross
      - libc6-dev-arm64-cross
      - libc6-dev-powerpc-cross
      - g++-9
      - qemu
      - lcov
      - mingw-w64
      - gcc-mingw-w64-x86-64 
      - g++-mingw-w64-x86-64
      - wine-stable
      - wine32
      - libogg-dev

os:
    - linux

compiler:
    - g++

script:
    - travisTest/Win/test.sh
    - travisTest/Linux/test.sh
